### ISSUE TITLE
Sorting tables

### ISSUE THREAD

**Issue by NilsJPWerner** [qor5/admin#188]
Hi, your project looks very interesting and potentially a way for us to move off the original qor. However I could not find a way to sort tables by a column. Is that not supported yet?

**Comment by xuxinx** [comment]
Hi @NilsJPWerner , sorting tables is configured by setting up OrderableFields on ListingBuilder https://github.com/qor5/admin/blob/0b643584f6d0743f4067f35b4230637fb15be892/presets/listing.go#L116.

And here is the example https://github.com/qor5/admin/blob/0b643584f6d0743f4067f35b4230637fb15be892/example/admin/input_demo_config.go#L23
