### ISSUE TITLE
Custom find handler like qor4

### ISSUE THREAD

**Issue by vunguyen260798** [qor5/admin#208]
Hello guys, I don't find any ways to custom find many handler before load list data of model. Because I want to preload some field before load to list data 
currently i just see code like this:
```
mb.Listing().Field("UserId").Label("User").ComponentFunc(func(obj interface{}, field *presets.FieldContext, ctx *web.EventContext) h.HTMLComponent {
		user := entity.User{}
		cid, _ := field.Value(obj).(string)
		if err := res.Db.Where("id = ?", cid).First(&user).Error; err != nil {
		}
		return h.Td(h.Text(user.Name))
	})
```

but with this code, every row will be call a query, this make low performance, what happen if i has 100 row and in each row, i need data from lots of reference field. Hope some update for this, Thanks

**Comment by moluuser** [comment]
Hi @vunguyen260798 , you can use `FetchFunc` like https://github.com/qor5/admin/blob/02d91858baf6dd4e1658dfd4c2cd6f40a50ae01b/presets/examples/setup.go#L359

**Comment by moluuser** [comment]
Hi @vunguyen260798 , you can use `SearchFunc` on listing like https://github.com/qor5/admin/blob/109a65ea2ff70d0b7df35318718fb880419cbd82/example/admin/config.go#L386

**Comment by moluuser** [comment]
The document is here: https://docs.qor5.com/basics/listing-customizations.html?h=SearchFunc
You can add the extra field you want in `SearchFunc`.

**Comment by vunguyen260798** [comment]
Thank @moluuser, it works fine, i will close this issue
