### ISSUE TITLE
custom a html page for a menu

### ISSUE THREAD

**Issue by vunguyen260798** [qor5/admin#221]
<img width="1455" alt="image" src="https://github.com/qor5/admin/assets/59702511/786ba6e6-acaa-47b8-bc01-1b3be941bbb1">
I have a html file for dashboard page, is there any way to serve that file on the right panel like above image?
I find it difficult to use htmlgo, because i integrate chartjs, table ,.. and I think it will take lots of time to convert html file to htmlgo. so i just want to use my available html file, Thanks

**Comment by xuxinx** [comment]
Hi @vunguyen260798 ,
You can convert your raw HTML content to `HTMLComponent` using [htmlgo.RawHTML](https://pkg.go.dev/github.com/theplant/htmlgo#RawHTML).

**Comment by vunguyen260798** [comment]
hm, I come up with the idea using `<iframe src="{link_to_report_page}"> `, I think this way is appropriate with me. anyway, thanks for responding @xuxinx
