### ISSUE TITLE
create multiple file field

### ISSUE THREAD

**Issue by vunguyen260798** [qor5/admin#238]
hello guys, I have this model like this:
**Product**{
 id uuid
images []string
...
}

how can I create a field upload multiple images and save path to `images` field? please give me some instruction or keyword for this

**Comment by xuxinx** [comment]
hi @vunguyen260798 , 
You can use `VInputFile` with [multiple=true](https://v2.vuetifyjs.com/en/components/file-inputs/#multiple) to upload multiple files at once and then handle them in the SetterFunc, example code: https://github.com/qor5/admin/blob/5d989e8388544f54755969726a3c594e68ea8605/example/admin/input_demo_config.go#L125. 
Alternatively, you can use the `media library` along with the `list editor` to upload images. This allows image preview and single uploads. example code:
https://github.com/qor5/admin/blob/5d989e8388544f54755969726a3c594e68ea8605/example/admin/customer_config.go#L14
