### ISSUE TITLE
Remove usages of unlicensed code from reflectutils

### ISSUE THREAD

**Issue by ahaasler** [qor5/admin#244]
Hi, _qor5/admin_ uses reflectutils, which does not provide a licence file, notice or headers. Until sunfmin/reflectutils#1 is resolved _qor5/admin_ should remove all usages of reflectutils code as it is copyrighted by @sunfmin and not properly licensed with a compatible open source licence, making _qor5/admin_ not really redistributable nor used under the MIT licence.

_elastic/go-licence-detector_ can be used to check dependency licences:

```bash
go list -m -json all | go-licence-detector -includeIndirect -depsOut=dependencies.asciidoc -noticeOut=NOTICE.txt
```

**Comment by sunfmin** [comment]
Added license to reflectutils
